server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/wallet
        username: wallet
        password: wallet
    flyway:
        enabled: true
        locations:
          - db.migration
