server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5430/wallet
        username: postgres
        password: postgres
    flyway:
        enabled: true
        locations:
          - db.migration
